services:
  skuld:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - HOSTNAME=0.0.0.0
    ports:
      - "${PORT}:${PORT}"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
