version: '3.8'
services:
  skuld:
    build: .
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
